[package]
name = "hakaii"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
fastnbt = "2.4.4"
fs_extra = "1.3.0"
linearify = "0.1.6"
serde = "1.0.164"

[profile.release]
debug = true
debug-assertions = true
